import { useState } from "react";
import { Zap } from "lucide-react";

// hooks
import { useSignalsByWeek, useAvailableWeeks } from "../hooks/useSignals";
import { MOCK_WEEK_RESPONSE, MOCK_WEEKS_RESPONSE } from "../api/signals-mock";
import { WeekSelector } from "../components/week-selector";
import { SignalStatsBar } from "../components/signal-stats-bar";
import { NiftyFilterBanner } from "../components/nifty-filter-banner";
import { SignalTable } from "../components/signal-table";



// mock fallback (remove once backend is live)
// import { MOCK_WEEK_RESPONSE, MOCK_WEEKS_RESPONSE } from "../api/signalsMock";

/* ─────────────────────────────────────────────
   FLAG: flip to false once the API is live
───────────────────────────────────────────── */
const USE_MOCK = true;

export function SignalsPage() {
  // Default to the most recent week
  const latestWeek = MOCK_WEEKS_RESPONSE.weeks[0].weekStart;
  const [selectedWeek, setSelectedWeek] = useState<string>(latestWeek);

  /* ── data ── */
  const weeksQuery = useAvailableWeeks();
  const signalsQuery = useSignalsByWeek(USE_MOCK ? null : selectedWeek);

  const weeks = USE_MOCK
    ? MOCK_WEEKS_RESPONSE.weeks
    : (weeksQuery.data?.weeks ?? []);
  const weekData = USE_MOCK ? MOCK_WEEK_RESPONSE : signalsQuery.data;
  const isLoading = USE_MOCK ? false : signalsQuery.isLoading;
  const isError = USE_MOCK ? false : signalsQuery.isError;

  return (
    <div className="px-8 py-8 space-y-6 max-w-[1600px]">
      {/* ── HERO ── */}
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-muted-foreground">
            <span className="size-1.5 rounded-full bg-primary animate-pulse" />
            PULSE BREAKER · Weekly Signals
          </div>
          <h1 className="mt-2 text-3xl md:text-4xl font-semibold">
            Signal Feed
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Breakout signals generated by the PULSE BREAKER engine ·{" "}
            <span className="text-foreground">
              {weeks.find((w) => w.weekStart === selectedWeek)?.weekLabel ??
                "—"}
            </span>
          </p>
        </div>

        {/* Strategy tag */}
        <div className="flex items-center gap-2 rounded-lg border border-border/60 bg-card/60 px-3 py-2 text-xs">
          <Zap className="size-3.5 text-primary" />
          <div>
            <p className="font-medium">PULSE BREAKER</p>
            <p className="text-muted-foreground">
              2C entry · 10C exit · 1.3× vol · Trail +6%
            </p>
          </div>
        </div>
      </div>

      {/* ── WEEK SELECTOR ── */}
      <WeekSelector
        weeks={weeks}
        selectedWeek={selectedWeek}
        onChange={setSelectedWeek}
      />

      {/* ── LOADING / ERROR ── */}
      {isLoading && (
        <div className="flex items-center justify-center h-48 text-muted-foreground text-sm">
          Loading signals…
        </div>
      )}
      {isError && (
        <div className="flex items-center justify-center h-48 text-destructive text-sm">
          Failed to load signals. Please try again.
        </div>
      )}

      {/* ── CONTENT ── */}
      {weekData && (
        <>
          {/* KPI cards */}
          <SignalStatsBar response={weekData} />

          {/* Nifty filter banner */}
          <NiftyFilterBanner
            niftyAboveEma={weekData.niftyAboveEma}
            niftyClose={weekData.niftyClose}
            niftyEma20w={weekData.niftyEma20w}
          />

          {/* Signal table */}
          <SignalTable signals={weekData.data} />
        </>
      )}
    </div>
  );
}
