import { type Setup } from "../types/playbook.types";

export const USE_MOCK = true;

export const mockSetups: Setup[] = [
  {
    id: "p1",
    name: "Stage-2 Breakout",
    tag: "S2-BO",
    bias: "Long",
    timeframe: "Positional",
    status: "Active",
    category: "Trend Following",
    pinned: true,
    description:
      "Weinstein-style breakout from a tight base after a clean stage-1 accumulation. High-volume thrust above pivot with rising 30W SMA.",
    trades: 42,
    winRate: 57.1,
    avgR: 1.82,
    expectancy: 4250,
    maxDD: 6.4,
    lastUsed: "18 Jun 2026",
    entry: [
      "Price above rising 30W & 10W SMA",
      "Tight 6–10 week base, ATR contraction",
      "Breakout on ≥ 1.8× avg daily volume",
      "Relative strength > 80 vs Nifty 500",
    ],
    exit: [
      "Trail under last structure low (swing)",
      "Partial 50% at 2R, runner on 10W SMA",
      "Full exit on close below 10W SMA",
    ],
    invalidate: [
      "Breakout fails & closes back inside base",
      "Daily candle range > 2× ATR against you",
    ],
    risk: {
      perTrade: "0.75% of equity",
      stop: "Structure low − 0.25 × ATR(14)",
      rr: "Min 1 : 2.5",
      position: "Max 8% of equity",
    },
    checklist: [
      { label: "Sector in stage-2", done: true },
      { label: "No earnings within 5 sessions", done: true },
      { label: "Index above 200 DMA", done: true },
      { label: "Liquidity > ₹25 Cr / day", done: true },
      { label: "Risk-on breadth confirmed", done: false },
    ],
  },
  {
    id: "p2",
    name: "VCP Pocket Pivot",
    tag: "VCP-PP",
    bias: "Long",
    timeframe: "Swing",
    status: "Active",
    category: "Momentum",
    pinned: true,
    description:
      "Minervini-style volatility contraction with a pocket pivot inside the handle. Entry on the first high-volume up day reclaiming the 10 DMA.",
    trades: 31,
    winRate: 61.3,
    avgR: 1.45,
    expectancy: 3120,
    maxDD: 4.9,
    lastUsed: "20 Jun 2026",
    entry: [
      "3+ contractions, each tighter than the last",
      "Pocket pivot inside the final contraction",
      "Volume > highest down-volume of prior 10 days",
      "Close in top 25% of day's range",
    ],
    exit: [
      "Stop below pivot low / 10 DMA",
      "Sell into climactic 3-day exhaustion",
      "Trail with 21 EMA once at 2R",
    ],
    invalidate: [
      "Loss of 10 DMA on heavy volume",
      "Wide-and-loose action returns",
    ],
    risk: {
      perTrade: "0.5% of equity",
      stop: "Tight: 4–6% from entry",
      rr: "Min 1 : 3",
      position: "Max 6% of equity",
    },
    checklist: [
      { label: "Tightness in last 5 bars", done: true },
      { label: "RS line at new high", done: true },
      { label: "Group leader confirmed", done: true },
      { label: "Earnings clear", done: false },
    ],
  },
  {
    id: "p3",
    name: "Opening Range Reversal",
    tag: "ORR",
    bias: "Both",
    timeframe: "Intraday",
    status: "Active",
    category: "Mean Reversion",
    pinned: false,
    description:
      "Fade exhaustion at the opening range extreme after a gap, with a failure test back into the prior day's value area.",
    trades: 88,
    winRate: 48.9,
    avgR: 1.1,
    expectancy: 980,
    maxDD: 8.2,
    lastUsed: "22 Jun 2026",
    entry: [
      "Gap > 0.6% beyond prior day value area",
      "Failure test of OR high/low in first 30 min",
      "Reclaim of VWAP on the reversal candle",
    ],
    exit: [
      "T1: opposite OR extreme",
      "T2: prior day VWAP",
      "Hard stop above/below failure wick",
    ],
    invalidate: [
      "Sustained acceptance beyond OR (> 15 min)",
      "VWAP slope continues with trend",
    ],
    risk: {
      perTrade: "0.4% of equity",
      stop: "12–18 bps from entry",
      rr: "Min 1 : 1.5",
      position: "Max 4% of equity",
    },
    checklist: [
      { label: "Index direction neutral", done: true },
      { label: "No major event at 9:30", done: true },
      { label: "Spread < 5 bps", done: true },
    ],
  },
  {
    id: "p4",
    name: "Earnings Drift Continuation",
    tag: "PEAD",
    bias: "Long",
    timeframe: "Swing",
    status: "Active",
    category: "Event Driven",
    pinned: false,
    description:
      "Post-earnings announcement drift: ride a high-quality beat with strong guidance for 5–20 sessions of momentum continuation.",
    trades: 24,
    winRate: 66.7,
    avgR: 1.95,
    expectancy: 5640,
    maxDD: 5.1,
    lastUsed: "12 Jun 2026",
    entry: [
      "Beat on revenue, EPS & guidance",
      "Gap-up holds for first session, close > open",
      "Volume > 3× ADV on report day",
    ],
    exit: [
      "T1: 1.5R partial, T2: 3R partial",
      "Trail under 8 EMA on 1H",
      "Time stop: 15 sessions",
    ],
    invalidate: [
      "Gap fills within 2 sessions",
      "Sector-wide compression starts",
    ],
    risk: {
      perTrade: "0.6% of equity",
      stop: "Below report-day low",
      rr: "Min 1 : 2",
      position: "Max 7% of equity",
    },
    checklist: [
      { label: "Surprise > 8%", done: true },
      { label: "No prior gap exhaustion", done: true },
      { label: "Analyst upgrades incoming", done: false },
    ],
  },
  {
    id: "p5",
    name: "Index Short Distribution",
    tag: "IDX-SD",
    bias: "Short",
    timeframe: "Swing",
    status: "Paused",
    category: "Trend Following",
    pinned: false,
    description:
      "Short index futures on confirmed stage-4 distribution: lower highs, breadth deterioration and a failed bounce at the declining 50 DMA.",
    trades: 11,
    winRate: 45.5,
    avgR: 1.3,
    expectancy: 2100,
    maxDD: 9.7,
    lastUsed: "02 May 2026",
    entry: [
      "Distribution count ≥ 5 in 25 sessions",
      "Failed bounce at 50 DMA, lower high",
      "Advance/Decline < 0.7 for 5 sessions",
    ],
    exit: [
      "Cover at prior swing low",
      "Trail above 8 EMA on daily",
      "Hard cover above 50 DMA",
    ],
    invalidate: ["Index reclaims 50 DMA on volume", "Breadth thrust > 2:1 up"],
    risk: {
      perTrade: "0.5% of equity",
      stop: "Above failed-bounce high",
      rr: "Min 1 : 2",
      position: "Max 1 lot per ₹10L",
    },
    checklist: [
      { label: "VIX rising", done: true },
      { label: "Defensives outperforming", done: false },
    ],
  },
  {
    id: "p6",
    name: "Pullback to 20 EMA",
    tag: "PB-20",
    bias: "Long",
    timeframe: "Swing",
    status: "Draft",
    category: "Trend Following",
    pinned: false,
    description:
      "Buy the first orderly pullback to the rising 20 EMA in a leading stock, with a hammer or inside-bar trigger.",
    trades: 0,
    winRate: 0,
    avgR: 0,
    expectancy: 0,
    maxDD: 0,
    lastUsed: "—",
    entry: [
      "Uptrend with rising 20/50 EMA",
      "3–5 bar orderly pullback to 20 EMA",
      "Reversal candle with volume",
    ],
    exit: ["Stop below pullback low", "Trail under 20 EMA"],
    invalidate: ["Close below 50 EMA"],
    risk: {
      perTrade: "0.5% of equity",
      stop: "1.2 × ATR(14)",
      rr: "Min 1 : 2",
      position: "Max 6% of equity",
    },
    checklist: [
      { label: "Define backtest window", done: false },
      { label: "Forward-test 10 trades", done: false },
    ],
  },
];
